# Generated by Django 4.1.7 on 2023-04-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Documento', models.TextField(max_length=30)),
                ('Nombre', models.TextField(max_length=30)),
                ('Apellido', models.TextField(max_length=30)),
                ('Correo', models.TextField(max_length=30)),
                ('Celular', models.TextField(max_length=30)),
            ],
        ),
    ]
