# Generated by Django 4.1.7 on 2023-05-23 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppBanco', '0003_alter_credito_plazo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Usuario', models.TextField(max_length=30)),
                ('Clave', models.TextField(max_length=30)),
                ('Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBanco.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.TextField(max_length=30)),
                ('Apellido', models.TextField(max_length=30)),
                ('Correo', models.TextField(max_length=30)),
                ('Celular', models.TextField(max_length=30)),
                ('Rol', models.TextField(max_length=30)),
                ('Documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AppBanco.usuario')),
            ],
        ),
    ]
