# Generated by Django 4.1.7 on 2023-08-03 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppBanco', '0005_auto_20230725_0943'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='User',
        ),
    ]
